package by.work.jefu;

/**
 * Romance fiction.
 */
public enum Romance implements Fiction {
    CONTEMPORARY_ROMANCE, HISTORICAL_ROMANCE, ROMANTIC_SUSPENSE, PARANORMAL_ROMANCE, 
    SCIENCE_FICTION_ROMANCE, FANTASY_ROMANCE, TIME_TRAVEL_ROMANCES, INSPIRATIONAL_ROMANCE, MULTICULTURAL_ROMANCE;
}
